import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ program: string }> }
) {
  try {
    const { program: rawProgram } = await params
    const program = decodeURIComponent(rawProgram)
    const searchParams = request.nextUrl.searchParams
    const sort = searchParams.get('sort') || 'newest' // newest, trending, most-commented
    const page = searchParams.get('page') || '1'
    const limit = 20

    // Validate program
    const validPrograms = ['YSMP', 'Thrive Tribe', 'Healing Centre']
    if (!validPrograms.includes(program)) {
      return NextResponse.json(
        { error: 'Invalid program' },
        { status: 400 }
      )
    }

    const skip = (parseInt(page) - 1) * limit

    // Sort logic
    let orderBy: Record<string, unknown> = { createdAt: 'desc' } // newest by default
    if (sort === 'trending') {
      orderBy = { likes: { _count: 'desc' } }
    } else if (sort === 'most-commented') {
      orderBy = { comments: { _count: 'desc' } }
    }

    const [posts, total] = await Promise.all([
      prisma.communityPost.findMany({
        where: {
          program,
          visibility: 'public',
        },
        include: {
          author: {
            select: {
              id: true,
              name: true,
              profile: { select: { avatar: true, program: true, badges: true } },
            },
          },
          _count: {
            select: { likes: true, comments: true },
          },
          celebrationData: {
            select: { isAutoGenerated: true },
          },
        },
        skip,
        take: limit,
        orderBy,
      }),
      prisma.communityPost.count({
        where: {
          program,
          visibility: 'public',
        },
      }),
    ])

    return NextResponse.json(
      {
        posts: posts.map((p) => ({
          ...p,
          likeCount: p._count.likes,
          commentCount: p._count.comments,
        })),
        total,
        page: parseInt(page),
        limit,
        hasMore: skip + limit < total,
        program,
      },
      { status: 200 }
    )
  } catch (error) {
    console.error('Program feed fetch error:', error)
    return NextResponse.json(
      { error: 'Failed to fetch program feed' },
      { status: 500 }
    )
  }
}
